
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AngganaApsari
 */
public class Frame1 extends javax.swing.JFrame {
    String temp="";
    Double ti, bt ,h1;
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tinggi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bb = new javax.swing.JTextField();
        kideal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        hasil = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        saran = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cl = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(tinggi);
        tinggi.setBounds(170, 74, 45, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(100, 251, 190, 15);
        getContentPane().add(bb);
        bb.setBounds(170, 112, 45, 30);

        kideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kidealActionPerformed(evt);
            }
        });
        getContentPane().add(kideal);
        kideal.setBounds(309, 238, 50, 30);

        jLabel12.setText("cm");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(219, 77, 30, 14);

        jLabel13.setText("kg");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(364, 251, 30, 14);

        jLabel14.setText("kg");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(219, 115, 40, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 255));
        jLabel15.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(160, 280, 180, 15);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Perempuan");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(170, 150, 100, 23);
        getContentPane().add(hasil);
        hasil.setBounds(58, 306, 360, 30);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Laki - laki");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(281, 150, 90, 23);
        getContentPane().add(saran);
        saran.setBounds(58, 344, 360, 30);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(74, 202, 80, 23);

        jLabel16.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(180, 10, 120, 14);

        jLabel17.setText("Nama");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(61, 39, 40, 14);

        jLabel18.setText("Tinggi");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(62, 77, 40, 14);

        jLabel19.setText("Berat Badan");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(64, 115, 90, 14);

        jLabel20.setText("Jenis Kelamin");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(60, 144, 90, 30);

        cl.setText("Coba Lagi");
        cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clActionPerformed(evt);
            }
        });
        getContentPane().add(cl);
        cl.setBounds(202, 202, 90, 23);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(170, 36, 180, 30);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(337, 202, 70, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void kidealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kidealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kidealActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        if (nama.getText().equals("")||tinggi.getText().equals("")
                
                ||bb.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data harus diisikan semua");
        }else if(jRadioButton3.isSelected()||jRadioButton4.isSelected()){
            try {
                Proses();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Inputan ada yang belum diisi");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Radio Button harus dipilih");
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        tinggi.setText("");
        bb.setText("");
        kideal.setText("");
        hasil.setText("");
        saran.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_clActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cl;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kideal;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.parseDouble(tinggi.getText());
        bt = Double.parseDouble(bb.getText());
        
        if (jRadioButton4.isSelected()) {
            h1 = (ti - 100) * 1;
        } else if (jRadioButton3.isSelected()) {
            h1 = (ti - 104) * 1;
        }
        temp = Double.toString(h1.intValue());
        
        if (h1 < bt) {
            kideal.setText(temp);
            hasil.setText("Maaf" + nama.getText() + " , Sepertinya anda Overweight");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkolestrol");
        } else if (h1 > bt) {
            kideal.setText(temp);
            hasil.setText("Maaf" + nama.getText() + " , Sepertinya anda Underweight");
            saran.setText("Banyaklah mengkonsumsi makanan yang berkabohidrat"); 
        } else {
            kideal.setText(temp);
            hasil.setText("Hallo" + nama.getText() + " , Berat badan anda sudah ideal");
            saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat"); 
        }
        
        //To change body of generated methods, choose Tools | Templates.
    }
}
